### ISSUE TITLE
Support ARM and Aarch64

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.chess#1]
We should try and re-enable arm builds when possible.

**Comment by mcatanzaro** [comment]
I have no clue why ARM builds are disabled.

Also not sure why we are bundling librsvg, gdk-pixbuf, and Rust? All of these are already provided by the runtime.

**Comment by TingPing** [comment]
> Also not sure why we are bundling librsvg, gdk-pixbuf, and Rust? All of these are already provided by the runtime.

I commented on the review but `librsvg` is only needed for Vala bindings, Rust isn't in the runtime, but yea the rest of `librsvg` and `gdk-pixbuf` should not be there.

**Comment by Zlopez** [comment]
> I have no clue why ARM builds are disabled.

This is the log from flathub build bot https://flathub.org/builds/#/builders/2/builds/3002
It failed on mismatch in types.

**Comment by Zlopez** [comment]
> I commented on the review but librsvg is only needed for Vala bindings, Rust isn't in the runtime (it uses the sdk extension), but yea the rest of librsvg and gdk-pixbuf should not be there.

When I removed the `gdk-pixbuf` from flatpak, I got this error:
```
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libpixbufloader-svg.la '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders'
libtool: warning: relinking 'libpixbufloader-svg.la'
libtool: install: (cd /run/build/librsvg/gdk-pixbuf-loader; /bin/sh "/run/build/librsvg/libtool"  --silent --tag CC --mode=relink gcc -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/pango-1.0 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/libcroco-0.6 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libxml2 -O2 -g -avoid-version -module -L/app/lib -o libpixbufloader-svg.la -rpath /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders libpixbufloader_svg_la-io-svg.lo ../librsvg-2.la -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lpng16 -lgdk_pixbuf-2.0 -lgio-2.0 -lpangocairo-1.0 -lcairo -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lfontconfig -lfreetype -lcroco-0.6 -lglib-2.0 -lxml2 )
libtool: install: /usr/bin/install -c .libs/libpixbufloader-svg.soT /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
/usr/bin/install: cannot remove '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so': Read-only file system
make[3]: *** [Makefile:527: install-gdk_pixbuf_moduleLTLIBRARIES] Error 1
make[3]: Leaving directory '/run/build/librsvg/gdk-pixbuf-loader'
make[2]: *** [Makefile:752: install-am] Error 2
make[2]: Leaving directory '/run/build/librsvg/gdk-pixbuf-loader'
make[1]: *** [Makefile:1725: install-recursive] Error 1
make[1]: Leaving directory '/run/build/librsvg'
make: *** [Makefile:2031: install] Error 2
```

When I removed the `libsvrg` I got this:
```
error: Package `librsvg-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)      
[16/31] Compiling C object 'lib/lib@@libchess@sta/meson-generated_chess-pgn.c.o'.                            
ninja: build stopped: subcommand failed.                                                        
Error: module gnome-chess: Child process exited with code 1
```

The flatpak doesn't build if I remove either of those.

**Comment by TingPing** [comment]
All you want from `librsvg` is the single generated VAPI file, nothing else. If you only install that then you don't need to deal with rust or gdk-pixbuf loaders, etc.

**Comment by Zlopez** [comment]
@TingPing 
I need to look how I can do this.

**Comment by mcatanzaro** [comment]
Path of least resistance would be to fix the SDK and remove all the bundled libraries (except gnuchess).

> I commented on the review but librsvg is only needed for Vala bindings, Rust isn't in the runtime (it uses the sdk extension), but yea the rest of librsvg and gdk-pixbuf should not be there.

The master SDK does build librsvg with --enable-vala, see https://gitlab.gnome.org/GNOME/gnome-sdk-images/blob/master/org.gnome.Sdk.json.in#L397. But it's not built for gnome-3-28 for some reason. I've just backported it to gnome-3-28 so it might be available as soon as tomorrow, if it builds.

**Comment by Zlopez** [comment]
@mcatanzaro 
Thanks for information. I will watch this.
