### ISSUE TITLE
Two times listed on flathub

### ISSUE THREAD

**Issue by rugk** [flathub/org.gnome.Chess#10]
This is two times listed on flathub with two icons… :thinking: This is quite strange.

https://flathub.org/apps/details/org.gnome.Chess
https://flathub.org/apps/details/org.gnome.chess

**Comment by rugk** [comment]
Okay, this seems to be caused by https://github.com/flathub/org.gnome.Chess/issues/2. The issue was also already mentioned there, but as the issue still persists, I guess it's better to have/use this open issue here.

**Comment by mcatanzaro** [comment]
Well we now can do <provides><id>oldname.desktop</id></provides> in the appstream metadata. flathub could have a chance if we add that.

**Comment by mcatanzaro** [comment]
I've added `<provides><id>gnome-chess.desktop</id></provides>` to the upstream appdata file.

But I'm actually not really sure how that's going to help flathub with this mess. You could patch in a provides for the flathub-specific lowercase org.gnome.chess, I suppose.

**Comment by Zlopez** [comment]
This is actually issue with flathub database. See https://github.com/flathub/flathub/issues/981

I marked `org.gnome.chess` as EOL and created a new repository for `org.gnome.Chess`, but the old one is still on the flathub, which is confusing.

**Comment by rugk** [comment]
So I'll close this as a duplicate of https://github.com/flathub/flathub/issues/981
