### ISSUE TITLE
Add stockfish support

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/org.gnome.Chess#13]
Please add stockfish as an alternative to gnuchess. If you are ok with it but you don't have the time then I can try to look into it and do a pull request if I am successful.

**Comment by Zlopez** [comment]
I based this flatpak on the upstream flatpak manifest, but I'm not sure how you want to add an alternative. Does GNOME chess allow you to actually switch this?

If you want to play with it, you're welcome.

**Comment by ThanosApostolou** [comment]
Yeah it supports it. Here's screenshot from the repositories' package:
![gnome-chess-stockfish](https://user-images.githubusercontent.com/21288843/66485879-35405e80-eab2-11e9-9be9-ccbaf551164f.png)


I think it just needs to detect the stockfish binary in order to be able to select it, so an extra module which installs it like gnuchess should do the trick. I will try to play with it later and do a pull request.

**Comment by Zlopez** [comment]
Thanks for the info, I didn't knew about this.

**Comment by mcatanzaro** [comment]
FWIW I think a reasonable selection of engines would be GNU Chess, Phalanx (default in openSUSE, unless that's changed), and Stockfish.

**Comment by ThanosApostolou** [comment]
fixed by https://github.com/flathub/org.gnome.Chess/pull/14

**Comment by cirosantilli** [comment]
BTW for the Googlers, the option is now under New Game, not preferences, it just stores settings from the last game after that:

![Screenshot from 2023-02-25 10-37-31](https://user-images.githubusercontent.com/1429315/221352403-a4afa44c-32ee-4d45-9eca-f05cd9ff60ac.png)
