### ISSUE TITLE
Uppercase?

### ISSUE THREAD

**Issue by mcatanzaro** [flathub/org.gnome.Chess#2]
I just renamed the upstream flatpak ID from "org.gnome.chess" to "org.gnome.Chess". Maybe flatpak should follow, while the app is still fresh here?

Shame we don't have more clear guidelines for capitalization.

**Comment by AsciiWolf** [comment]
Yeah, this Flatpak needs to be renamed, it's broken since 3.32 (see #8) because of this.

**Comment by mcatanzaro** [comment]
> Shame we don't have more clear guidelines for capitalization.

Note we're trying to standardize GNOME on org.gnome.Capital rather than org.gnome.lowercase so there will almost surely be more renames. Lots of games got renamed for 3.32, even gschemas were renamed to match.

**Comment by ramcq** [comment]
> Note we're trying to standardize GNOME on org.gnome.Capital rather than org.gnome.lowercase so there will almost surely be more renames. Lots of games got renamed for 3.32, even gschemas were renamed to match.

What did you do for pinned desktop icons in Shell?

**Comment by alexlarsson** [comment]
> > Shame we don't have more clear guidelines for capitalization.
> 
> Note we're trying to standardize GNOME on org.gnome.Capital rather than org.gnome.lowercase so there will almost surely be more renames. Lots of games got renamed for 3.32, even gschemas were renamed to match.

Mass renaming the names is gonna cause all sorts of issues. The app id in flatpak gets encoded in filenames that are persisted in places, but its also used for the desktop file which is used in things like recently used and pinned apps as well as mime config.

This seems to me like a whole lot of churn that will break things for not a huge amount of gain.

**Comment by mcatanzaro** [comment]
> What did you do for pinned desktop icons in Shell?

I only renamed the app ID used by the upstream flatpak manifest (and just one week after it was added to flathub, as you can see from the date of this issue report; that would have been the best time to have handled this). I didn't touch the desktop file; that came in https://gitlab.gnome.org/GNOME/gnome-chess/merge_requests/2. That's unrelated to the manifest rename IMO, since it was previously gnome-chess.desktop, not org.gnome.chess.desktop. But many, many other GNOME apps have been renaming to org.gnome.Foo.desktop; there's clearly a movement to do so, and I didn't see any reason to reject the MR.

Anyway, the shell rename list was not updated as it should have been:

https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/js/ui/appFavorites.js

The rename list is too easy to forget and the consequences of forgetting are very minor, so it's not a big deal, but yes it should have been updated. You can see a huge number of non-games apps doing desktop renames there, so the platform must already be prepared to expect that.

**Comment by AsciiWolf** [comment]
Could someone update _appFavorites.js_ in gnome-shell? I would do it, unfortunately I am currently not at home, using only my phone.

**Comment by AsciiWolf** [comment]
I have [opened](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1160) an issue in gnome-shell for the _appFavorites.js_ update.

**Comment by Zlopez** [comment]
Repository was renamed.

**Comment by AsciiWolf** [comment]
Hmm, it seems that both [old](https://flathub.org/apps/details/org.gnome.chess) and [new](https://flathub.org/apps/details/org.gnome.Chess) GNOME Chess is now shown on the Flathub website. This is quite confusing.

**Comment by barthalion** [comment]
Marked the old app-id EOL again, manually this time. Let's see if store picks it up in a couple of hours.

**Comment by AsciiWolf** [comment]
@barthalion Unfortunately, still the same issue. :-(
