### ISSUE TITLE
Remove armv7 from manifest 

### ISSUE THREAD

**Issue by vchernin** [flathub/org.gnome.Chess#32]
https://github.com/flathub/org.gnome.Chess/blob/42d64baf072e798a4d56b48a0184bbd69237a3bc/org.gnome.Chess.json#L53

Flathub doesn’t support armv7 anymore, only aarch64 and x86_64 currently.

**Comment by hfiguiere** [comment]
also `aarch64` is `armv8`

**Comment by hfiguiere** [comment]
nevermind stockfish in that package is too old.
